# Introduction

- Tömbök létrehozása
- Tömbök átméretezése, lekérdezések (vektor, mátrix, tenzor)
- Műveletek

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
print(a1)

[1 2 3]


In [6]:
a2 = np.array([[1,2.0,3.3],
               [4.,5.0,6.01]])

In [7]:
a2

array([[1.  , 2.  , 3.3 ],
       [4.  , 5.  , 6.01]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [12]:
a1 = a1.reshape(3,1)

In [13]:
a1.shape

(3, 1)

In [14]:
a1.dtype

dtype('int64')

In [15]:
a2.dtype

dtype('float64')

In [16]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.random.randint(5,10,(4,5))

array([[9, 7, 8, 7, 5],
       [8, 7, 6, 5, 5],
       [8, 5, 7, 8, 5],
       [8, 5, 8, 7, 7]])

In [22]:
np.random.rand(4,3)

array([[0.72917876, 0.18033951, 0.3887099 ],
       [0.6537144 , 0.93777714, 0.34653672],
       [0.85303415, 0.15763503, 0.737113  ],
       [0.36995713, 0.49253063, 0.21316804]])

In [23]:
np.exp(2.0)

7.38905609893065

In [24]:
np.exp(a1)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [25]:
np.log(a1)

array([[0.        ],
       [0.69314718],
       [1.09861229]])

In [26]:
A = np.array([[2,3,4],[97,12,32]])

In [27]:
A

array([[ 2,  3,  4],
       [97, 12, 32]])

In [29]:
B = np.random.rand(2,3)

In [30]:
B

array([[0.95290676, 0.57688267, 0.43161043],
       [0.73419012, 0.40885974, 0.58567289]])

In [31]:
A + B

array([[ 2.95290676,  3.57688267,  4.43161043],
       [97.73419012, 12.40885974, 32.58567289]])

In [32]:
B = B.reshape(3,2)

In [33]:
A @ B

array([[  4.83608376,   5.69902723],
       [110.69479213,  83.50943245]])

In [34]:
B.T

array([[0.95290676, 0.43161043, 0.40885974],
       [0.57688267, 0.73419012, 0.58567289]])

In [35]:
np.min(a2)

1.0

In [36]:
np.argmin(2)

0

In [37]:
a2 = np.random.randint(0,10,(4,3))

In [38]:
a2

array([[0, 3, 9],
       [3, 8, 3],
       [6, 5, 4],
       [6, 9, 8]])

In [39]:
np.argmin(a2)

0