In [1]:
import pandas as pd

In [2]:
cars = pd.Series(["BMW","Toyota","Honda"])

In [3]:
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [4]:
print(cars)

0       BMW
1    Toyota
2     Honda
dtype: object


In [5]:
a= 1.17
print(f"Az alma ara dollarban: {a}")

Az alma ara dollarban: 1.17


In [6]:
color = pd.Series(["Blue","Red","Green"])

In [7]:
color

0     Blue
1      Red
2    Green
dtype: object

In [8]:
car_data = pd.DataFrame({"Car type":cars,"Color":color})

In [9]:
car_data

Car type  Color
0      BMW   Blue
1   Toyota    Red
2    Honda  Green

In [10]:
dictionary_example = {
    "alma":2.2,
    "korte":1.7,
    "szilva":3.4}

In [11]:
dictionary_example["barack"] = 4.5

In [12]:
dictionary_example

{'alma': 2.2, 'korte': 1.7, 'szilva': 3.4, 'barack': 4.5}

In [13]:
pd.DataFrame([dictionary_example])

alma  korte  szilva  barack
0   2.2    1.7     3.4     4.5

In [14]:
dictionary_example = {"alma":[2.2, 3.9],
                      "korte":[3.3, 4.4]}

In [15]:
dictionary_example["alma"]

[2.2, 3.9]

In [16]:
pd.DataFrame(dictionary_example)

alma  korte
0   2.2    3.3
1   3.9    4.4

In [17]:
import numpy as np

In [18]:
X = np.random.rand(5,3)

In [19]:
X

array([[0.78667014, 0.48002152, 0.95490435],
       [0.96325194, 0.00330152, 0.81484932],
       [0.55653622, 0.65255763, 0.38690705],
       [0.48304071, 0.75415848, 0.71492297],
       [0.96752974, 0.45687879, 0.17336409]])

In [20]:
df_X = pd.DataFrame(X)

In [21]:
df_X

0         1         2
0  0.786670  0.480022  0.954904
1  0.963252  0.003302  0.814849
2  0.556536  0.652558  0.386907
3  0.483041  0.754158  0.714923
4  0.967530  0.456879  0.173364

In [22]:
Y = np.random.rand(6,7)*10

In [23]:
Y

array([[6.70160125, 4.23044169, 1.18794329, 3.92246629, 0.43203952,
        1.62566545, 4.32142442],
       [7.70905446, 0.73004806, 9.87083862, 4.75874392, 8.79396945,
        7.01538381, 5.90915011],
       [4.65289081, 5.67826645, 9.99140798, 3.23437207, 0.49430435,
        7.32863792, 5.10894663],
       [7.61473476, 8.33251065, 5.1576263 , 9.87623771, 0.54556304,
        8.74021419, 8.99229569],
       [5.51601768, 9.58943885, 6.90896829, 0.07376371, 7.27339962,
        1.98397591, 2.02248244],
       [7.1288801 , 6.57709956, 4.45874183, 0.07872873, 8.75452576,
        0.16631101, 3.25198444]])

In [24]:
df_X

0         1         2
0  0.786670  0.480022  0.954904
1  0.963252  0.003302  0.814849
2  0.556536  0.652558  0.386907
3  0.483041  0.754158  0.714923
4  0.967530  0.456879  0.173364

In [25]:
df_X.to_numpy()

array([[0.78667014, 0.48002152, 0.95490435],
       [0.96325194, 0.00330152, 0.81484932],
       [0.55653622, 0.65255763, 0.38690705],
       [0.48304071, 0.75415848, 0.71492297],
       [0.96752974, 0.45687879, 0.17336409]])

In [26]:
filename ="https://raw.githubusercontent.com/szbela87/ml_22_elteik/main/data/car-sales.csv"

In [27]:
car_sales = pd.read_csv(filename)

In [28]:
car_sales

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [29]:
car_sales.to_csv("autocskak.csv")

In [30]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [31]:
car_sales.describe()

Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [33]:
prices = car_sales["Price"]

In [36]:
prices = prices.replace("\$","",regex=True)

In [37]:
prices = prices.replace("[\,\.]","",regex=True)

In [38]:
prices

0     400000
1     500000
2     700000
3    2200000
4     350000
5     450000
6     750000
7     700000
8     625000
9     970000
Name: Price, dtype: object

In [39]:
prices = prices.astype(int)

In [41]:
prices = prices/100

In [42]:
prices

0     4000.0
1     5000.0
2     7000.0
3    22000.0
4     3500.0
5     4500.0
6     7500.0
7     7000.0
8     6250.0
9     9700.0
Name: Price, dtype: float64

In [43]:
car_sales["Price"] = prices

In [44]:
car_sales

Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   4000.0
1   Honda    Red          87899      4   5000.0
2  Toyota   Blue          32549      3   7000.0
3     BMW  Black          11179      5  22000.0
4  Nissan  White         213095      4   3500.0
5  Toyota  Green          99213      4   4500.0
6   Honda   Blue          45698      4   7500.0
7   Honda   Blue          54738      4   7000.0
8  Toyota  White          60000      4   6250.0
9  Nissan  White          31600      4   9700.0

In [45]:
car_sales.describe()

Odometer (KM)      Doors         Price
count      10.000000  10.000000     10.000000
mean    78601.400000   4.000000   7645.000000
std     61983.471735   0.471405   5379.407753
min     11179.000000   3.000000   3500.000000
25%     35836.250000   4.000000   4625.000000
50%     57369.000000   4.000000   6625.000000
75%     96384.500000   4.000000   7375.000000
max    213095.000000   5.000000  22000.000000

In [46]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Make           10 non-null     object 
 1   Colour         10 non-null     object 
 2   Odometer (KM)  10 non-null     int64  
 3   Doors          10 non-null     int64  
 4   Price          10 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 528.0+ bytes


In [47]:
car_sales.to_numpy()

array([['Toyota', 'White', 150043, 4, 4000.0],
       ['Honda', 'Red', 87899, 4, 5000.0],
       ['Toyota', 'Blue', 32549, 3, 7000.0],
       ['BMW', 'Black', 11179, 5, 22000.0],
       ['Nissan', 'White', 213095, 4, 3500.0],
       ['Toyota', 'Green', 99213, 4, 4500.0],
       ['Honda', 'Blue', 45698, 4, 7500.0],
       ['Honda', 'Blue', 54738, 4, 7000.0],
       ['Toyota', 'White', 60000, 4, 6250.0],
       ['Nissan', 'White', 31600, 4, 9700.0]], dtype=object)