# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
oneD = np.array([1,3,5,7])

# Create a 2-dimensional NumPy array using np.array()
twoD = np.array([[1,3],[5,7]])

# Create a 3-dimensional Numpy array using np.array()
threeD = np.array([[[1,3],[5,7]],[[7,5],[3,1]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
oneD.shape, oneD.ndim, oneD.dtype, oneD.size, type(oneD)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
twoD.shape, twoD.ndim, twoD.dtype, twoD.size, type(twoD)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
threeD.shape, threeD.ndim, threeD.dtype, threeD.size, type(threeD)

((2, 2, 2), 3, dtype('int64'), 8, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
twoDF = pd.DataFrame(twoD)
twoDF

0  1
0  1  3
1  5  7

In [7]:
# Create an array of shape (10, 2) with only ones
Ones = np.ones((10,2),int)
Ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
Zeros = np.zeros((7,2,3),int)
Zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
DivideByThree = np.arange(0,100,3)
DivideByThree

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
RandIntZeroTen = np.random.randint(0,10,size=(7,2))
RandIntZeroTen

array([[8, 9],
       [5, 7],
       [8, 3],
       [6, 4],
       [2, 0],
       [5, 5],
       [7, 4]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
RandFloatZeroOne = np.random.random((3,5))
RandFloatZeroOne

array([[0.85530744, 0.0337053 , 0.78546077, 0.02820679, 0.99813204],
       [0.58154689, 0.94208557, 0.0405321 , 0.238788  , 0.1453287 ],
       [0.46676683, 0.10253886, 0.79210713, 0.92489105, 0.75225161]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
RandFloatZeroTen = np.random.random((4,6))
RandFloatZeroTen

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
Array1 = np.random.randint(10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(Array1)

array([1, 2, 3, 4, 6, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
Array1[0,0]

2

In [15]:
# Get the first 2 rows of latest array you created
Array1[0:2,:]

array([[2, 6, 3, 8, 2, 4, 2],
       [6, 4, 8, 6, 1, 3, 8]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
Array1[:2,:2]

array([[2, 6],
       [6, 4]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
Array2 = np.random.randint(0,10,size=(3,5))
Ones1 = np.ones((3,5),int)

In [18]:
# Add the two arrays together
Array2 + Ones1

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [19]:
# Create another array of ones of shape (5, 3)
Ones2 = np.ones((5,3),int)

In [20]:
# Try add the array of ones and the other most recent array together

# Ones1 + Ones2, doesn't work because the array sizes don't match --> solution: reshape
Ones1 + np.reshape(Ones2,(3,5))

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
Ones3 = np.ones((3,5),int)
Ones3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# Subtract the new array of ones from the other most recent array
Ones2 - np.reshape(Ones3,(5,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
# Multiply the ones array with the latest array
np.matmul(Ones2,Array2)

array([[12, 23,  8,  6,  9],
       [12, 23,  8,  6,  9],
       [12, 23,  8,  6,  9],
       [12, 23,  8,  6,  9],
       [12, 23,  8,  6,  9]])

In [24]:
# Take the latest array to the power of 2 using '**'
Array2 ** Array2

array([[    46656,    823543,         4,         1,        27],
       [        1,    823543,        27,         1,      3125],
       [     3125, 387420489,        27,      3125,         1]])

In [25]:
# Do the same thing with np.square()
np.square(Array2)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(Array2)

3.8666666666666667

In [27]:
# Find the maximum of the latest array using np.max()
np.max(Array2)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(Array2)

0

In [29]:
# Find the standard deviation of the latest array
np.std(Array2)

2.578543947441829

In [30]:
# Find the variance of the latest array
np.var(Array2)

6.648888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
Array2 = Array2.reshape(3,5,1)
Array2

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
# Transpose the latest array
Array2.transpose()

array([[[6, 1, 5],
        [7, 7, 9],
        [2, 3, 3],
        [0, 1, 5],
        [3, 5, 1]]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
Intarray1 = np.random.randint(0,10,size=(3,3))
Intarray2 = np.random.randint(0,10,size=(3,2))

In [34]:
# Perform a dot product on the two newest arrays you created
np.dot(Intarray1,Intarray2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
Intarray4 = np.random.randint(0,10,(4,3))
Intarray5 = np.random.randint(0,10,(4,3))

In [36]:
# Perform a dot product on the two newest arrays you created
# np.dot(Intarray4,Intarray5) - the shapes of the matrixes are incorrect
# -> one of them needs to be transposed

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(Intarray4,np.transpose(Intarray5))

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
RandIntArray1 = np.random.randint(0,10,(3,3))
RandIntArray2 = np.random.randint(0,10,(3,3))

print(RandIntArray1, '\n\n' ,RandIntArray2)

[[6 6 7]
 [4 2 7]
 [5 2 0]] 

 [[2 4 2]
 [0 4 9]
 [6 6 8]]


In [39]:
# Compare the two arrays with '>'
RandIntArray1 > RandIntArray2

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
RandIntArray1 >= RandIntArray2

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [41]:
# Find which elements of the first array are greater than 7
RandIntArray1 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
# Which parts of each array are equal? (try using '==')
RandIntArray1 == RandIntArray2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
# Sort one of the arrays you just created in ascending order
RandIntArray1.sort()
RandIntArray1

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5]])

In [44]:
# Sort the indexes of one of the arrays you just created
RandIntArray2.argsort()
RandIntArray2

array([[2, 4, 2],
       [0, 4, 9],
       [6, 6, 8]])

In [45]:
# Find the index with the maximum value in one of the arrays you've created
RandIntArray1.argmax()

2

In [46]:
# Find the index with the minimum value in one of the arrays you've created
RandIntArray2.argmin()

3

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(RandIntArray1,axis=1)

array([2, 2, 2])

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(RandIntArray2,axis=0)

array([1, 0, 0])

In [49]:
# Create an array of normally distributed random numbers
NormalArray1 = np.linspace(0,10,5)
NormalArray1 = NormalArray1.astype(int)
NormalArray1

array([ 0,  2,  5,  7, 10])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
NormalArray2 = np.linspace(1,100,10)
NormalArray2 = NormalArray2.astype(int)
NormalArray2

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.