In [1]:
import numpy as np

In [12]:
neg_LpD_inv = np.array([[-1/4,0,0],[1/16,-1/4,0],[-1/32,1/8,-1/2]])
neg_LpD_inv

array([[-0.25   ,  0.     ,  0.     ],
       [ 0.0625 , -0.25   ,  0.     ],
       [-0.03125,  0.125  , -0.5    ]])

In [15]:
LpD_inv = np.array([[1/4,0,0],[-1/16,1/4,0],[1/32,-1/8,1/2]])
LpD_inv

array([[ 0.25   ,  0.     ,  0.     ],
       [-0.0625 ,  0.25   ,  0.     ],
       [ 0.03125, -0.125  ,  0.5    ]])

In [13]:
U = np.array([[0,2,1],[0,0,3],[0,0,0]])
U

array([[0, 2, 1],
       [0, 0, 3],
       [0, 0, 0]])

In [16]:
b = np.array([1,0,0])

In [14]:
np.matmul(neg_LpD_inv,U)

array([[ 0.     , -0.5    , -0.25   ],
       [ 0.     ,  0.125  , -0.6875 ],
       [ 0.     , -0.0625 ,  0.34375]])

In [10]:
-11/16

-0.6875

In [11]:
11/32

0.34375

In [17]:
np.matmul(LpD_inv,b)

array([ 0.25   , -0.0625 ,  0.03125])

In [32]:
512/128

4.0

In [33]:
512/16

32.0

In [34]:
1024/32

32.0

In [37]:
np.log(1/1000*12/16)/np.log(13/16)

34.65353190190371